name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  ansible:
    runs-on: ubuntu-latest
    env:
      ANSIBLE_SSH_KEY: ${{ secrets.ANSIBLE_SSH_KEY }}
    steps:
      - uses: actions/checkout@v3

      - name: Check Files
        run: ls -aR

      - name: Test Ansible
        run: ansible --version

      - name: Check Env
        run: env

     
